#PROJECT WAS CREATED WITH PYMAKE
#PYMAKE: https://github.com/EndMy5uffering/PyCmakeToolKit
#THIS FILE WILL BE OVERWRITTEN WHEN PYMAKE SCAN IS USED!
#CHANGES TO THIS FILE WILL NOT CARRY OVER
set(
	SOURCE_FILES_SRC_FOLDER
	./src/Main.cpp
)